# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=30, unique=True)),
                ('common_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coasters.Country')),
            ],
        ),
        migrations.CreateModel(
            name='RollerCoaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year_opened', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coasters.Park')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rollercoaster',
            unique_together=set([('name', 'park')]),
        ),
        migrations.AlterUniqueTogether(
            name='park',
            unique_together=set([('name', 'country')]),
        ),
    ]
