# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollercoaster',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coasters.Manufacturer'),
            preserve_default=False,
        ),
    ]
